api_platform:
  show_webby: false
  title: 'Srekcud eveTools API'
  description: 'Srekcud tooling to improve Eve Online experience'

  mapping:
    paths:
      - '%kernel.project_dir%/src/Entity'
#      - '%kernel.project_dir%/src/Model'
