framework:
    messenger:
        transports:
             identify-id:
               dsn: '%env(MESSENGER_TRANSPORT_DSN)%/%2f/identify-id'
             ravworks-stock:
               dsn: '%env(MESSENGER_TRANSPORT_DSN)%/%2f/ravworks-stock'
             ravworks-job:
               dsn: '%env(MESSENGER_TRANSPORT_DSN)%/%2f/ravworks-job'
             irl-link:
               dsn: '%env(MESSENGER_TRANSPORT_DSN)%/%2f/irl-link'



        routing:
             'App\Message\IdentifyIdMessage': identify-id
             'App\Message\RavworksStockMessage': ravworks-stock
             'App\Message\RavworksJobMessage': ravworks-job
             'App\Message\IndustryRavworksLinkMessage': irl-link

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
