services:
  webserver:
    image: nginx:alpine
    container_name: evetools-nginx
    working_dir: /var/www
    volumes:
        - $PWD:/var/www/
        - ./volumes/nginx:/etc/nginx/conf.d
    ports:
        - "${NETWORK_PREFIX}.1:80:80"
    networks:
        evetools:
            ipv4_address: ${NETWORK_PREFIX}.2

  php-cli:
    build: .docker/php-cli
#    image: evetools-cli:0.1
    container_name: evetools-php-cli
    working_dir: /var/www/
    command: /bin/true
    networks:
      evetools:
        ipv4_address: ${NETWORK_PREFIX}.4
    volumes:
      - ./volumes/composer-cache:/home/www-data/.composer/cache/:cached
      - ./volumes/composer-home:/home/www-data/.composer:cached
      - ./volumes/composer-home-root:/root/.composer:cached
      - ./volumes/shared:/tmp/shared:cached
      - $PWD:/var/www
  
  php-fpm:
    build: .docker/php-fpm
#    image: evetools-fpm:0.1
    container_name: evetools-php-fpm
    working_dir: /var/www/
    networks:
      evetools:
        ipv4_address: ${NETWORK_PREFIX}.5
    volumes:
      - ./volumes/php-fpm:/var/log/php:cached
      - .:/var/www/:cached

#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.21
#    container_name: evetools-es
#    environment:
#      - discovery.type=single-node
#      - "ES_JAVA_OPTS=-Xms1g -Xmx2g"
#    ports:
#      - ${NETWORK_PREFIX}.1:9200:9200
#      - ${NETWORK_PREFIX}.1:9300:9300
#    networks:
#      evetools:
#        ipv4_address: ${NETWORK_PREFIX}.9
#    volumes:
#      - es_files:/usr/share/elasticsearch/data:cached

#    docker run \
#    --publish 5601:5601 \
#    --network evetools \
#    --env "ELASTICSEARCH_HOSTS=http://10.169.0.1:9200" \
#    docker.elastic.co/kibana/kibana:7.17.21

  database:
    image: postgres:${POSTGRES_VERSION:-17}-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-api}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-!ChangeMe!}
      - POSTGRES_USER=${POSTGRES_USER:-api}
    ports:
      - "${NETWORK_PREFIX}.1:5432:5432"
    networks:
      evetools:
        ipv4_address: ${NETWORK_PREFIX}.50
    volumes:
      - db_data:/var/lib/postgresql/data:rw

  rabbitmq:
    image: rabbitmq:3.12.12-management-alpine
    container_name: evetools-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: evetools
      RABBITMQ_DEFAULT_PASS: evetools
    ports:
      - "15672:15672"
      - "15671:15671"
      - "5672:5672"
    networks:
      evetools:
        ipv4_address: ${NETWORK_PREFIX}.10
  
  # redis:
  #   image: redis:7.2.4-alpine3.19
  #   container_name: evetools-redis
  #   volumes:
  #     - ./volumes/redis/data:/data
  #   networks:
  #     evetools:
  #       ipv4_address: ${NETWORK_PREFIX}.11

volumes:
  es_files:
    driver: local
  db_data:

networks:
  evetools:
    name: evetools
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK_PREFIX}.0/24