services:
  webserver:
    image: nginx:alpine
    container_name: webserver-evetools
    working_dir: /var/www
    volumes:
        - $PWD:/var/www/
        - ./volumes/nginx:/etc/nginx/conf.d
    ports:
        - "${NETWORK_PREFIX}.1:80:80"
    networks:
        evetools:
            ipv4_address: ${NETWORK_PREFIX}.2

  php-cli:
    image: evetools-cli:0.1
    container_name: evetools-php-cli
    working_dir: /var/www/
    command: /bin/true
    networks:
      evetools:
        ipv4_address: ${NETWORK_PREFIX}.4
    volumes:
      - ./volumes/composer-cache:/home/www-data/.composer/cache/:cached
      - ./volumes/composer-home:/home/www-data/.composer:cached
      - ./volumes/composer-home-root:/root/.composer:cached
      - ./volumes/shared:/tmp/shared:cached
      - $PWD:/var/www
  
  php-fpm:
    image: evetools-fpm:0.1
    container_name: evetools-php-fpm
    working_dir: /var/www/
    networks:
      evetools:
        ipv4_address: ${NETWORK_PREFIX}.5
    volumes:
      - ./volumes/php-fpm:/var/log/php:cached
      - .:/var/www/:cached

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.21
    container_name: evetools-es
    environment:
      - discovery.type=single-node
    ports:
      - ${NETWORK_PREFIX}.1:9200:9200
      - ${NETWORK_PREFIX}.1:9300:9300
    networks:
      evetools:
        ipv4_address: ${NETWORK_PREFIX}.9
    volumes:
      - es_files:/usr/share/elasticsearch/data:cached

  # rabbitmq:
  #   image: rabbitmq:3.12.12-management-alpine
  #   container_name: evetools-rabbitmq
  #   environment:
  #     RABBITMQ_DEFAULT_USER: evetools
  #     RABBITMQ_DEFAULT_PASS: evetools
  #   networks:
  #     evetools:
  #       ipv4_address: ${NETWORK_PREFIX}.10
  
  # redis:
  #   image: redis:7.2.4-alpine3.19
  #   container_name: evetools-redis
  #   volumes:
  #     - ./volumes/redis/data:/data
  #   networks:
  #     evetools:
  #       ipv4_address: ${NETWORK_PREFIX}.11


networks:
  evetools:
    name: evetools
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK_PREFIX}.0/28